apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: k8s-preview-appset 
spec:
  generators:
    - pullRequest:
        github:
          owner: LapoElisacci
          repo: k8s-preview
          tokenRef:
            key: token
            secretName: github-token
        requeueAfterSeconds: 300
  template:
    metadata:
      name: 'k8s-preview-{{branch}}-{{number}}'
    spec:
      destination:
        namespace: 'k8s-preview-{{branch}}'
        server: 'https://kubernetes.default.svc'
      project: default
      source:
        path: . 
        repoURL: 'https://github.com/LapoElisacci/k8s-preview.git'
        targetRevision: HEAD
        helm:
          parameters:
            - name: namespace
              value: 'preview-{{branch}}'
            - name: version
              value: '{{head_sha}}'
      syncPolicy:
        automated:
          selfHeal: true
